name = "OpenDPTranslation"
version = "0.1.0"
defaultTargets = ["opendptranslation"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"

[[lean_lib]]
name = "OpenDPTranslation"

[[lean_exe]]
name = "opendptranslation"
root = "Main"
